### PR TITLE
Correct psr4 autoloading

### PR DESCRIPTION
**Pull request by Vincent--**
The filename needs to be the same as the class name if you want psr4 autoloading functionality to work

See http://culttt.com/2014/05/07/create-psr-4-php-package/

> The vendor-package namespace MAY map to any directory. The remaining portion of the fully-qualified class name MUST map the namespace names to identically-named directories, and MUST map the class name to an identically-named file ending in .php.

### CODE REVIEW

**Comment by ericmartel** [comment]
Thanks, I should have been more careful!

**Comment by Vincent--** [comment]
no pb, thanks for your modules :-)

**Comment by Vincent--** [comment]
Hey Eric !

Could you publish a release for that, please ?
Thanking you in advance.

Regards,
Vincent.

**Comment by ericmartel** [comment]
Hi Vincent!

Sorry for the delay, I pushed a release (and updated packagist by hand
since my hooks don't seem to work yet)

Thanks

**Pull request merged**
